### ISSUE TITLE
a bug

### ISSUE THREAD

**Issue by liewinme** [akonkol/tratto#1]
hi~
I use this framework, it is very great. I found a bug.
When the switch is not configured with a username, telnet will connect fail. I conducted the following fixes.In Connectivity.py of 24 lines.add 'password'.

```
i = self.connection.expect ([r "(? i) (username | login | password) [\ s:] +", pexpect.TIMEOUT, r "uthentication failed."])
```

**Comment by akonkol** [comment]
Added "password" to expect line int last commit
